//
//  Image+Extensions.swift
//  FemoCare
//
//  Created by MacMini on 06/01/2025.
//



import Foundation
import SwiftUI

extension Image {
    static var appImage = AppImage()
}
struct AppImage {
    let mostpopular = Image("MostPopular")
    let linkimage = Image("linkImage")
    let grayeye = Image("GrayEye")
    let grayeyeslash = Image("GrayEyeSlash")
    let crossbutton = Image("CrossButton")
    let loggout = Image("LoggOut")
    let service = Image("Service")
    let facebook = Image("Facebook")
    let instagram = Image("Instagram")
    let telegram = Image("Telegram")
    let twitter = Image("Twitter")
    let whatsapp = Image("WhatsApp")
    let checkmark = Image("CheckMark")
    let subscriptionwhite = Image("SubscriptionWhite")
    let passwordlock = Image("PasswordLock")
    let calendar1 = Image("Calendar1")
    let larry = Image("Larry")
    let logout = Image("Logout")
    let contactsupport = Image("ContactSupport")
    let subscription = Image("Subscription")
    let profileblack = Image("ProfileBlack")
    let calendar = Image("Calendar")
    let trash = Image("Trash")
    let receiptscanner = Image("ReceiptScanner")
    let deleteicon = Image("DeleteButton")
    let shopping = Image("Shopping")
    let homee = Image("Home")
    let receipts = Image("Receipts")
    let notifications = Image("Notifications")
    let settings = Image("Settings")
    let character = Image("Character")
    let autosorting = Image("AutoSorting")
    let plus = Image("Plus")
    let congratssheetimage = Image("CongratsBottomSheet")
    let profile = Image("Profile")
    let eye = Image("EyeFill")
    let eyeslash = Image("EyeSlash")
    let apple = Image("Apple")
    let google = Image("Google")
    let receipt = Image("Receipt")
    let ellipse = Image("Ellipse")
    let email = Image("Email")
    let lock = Image("Lock")
    let faceid = Image("FaceId")
}
//struct AppImage {
//    let test = Image("Test")
//    let cross = Image("Cross")
//    let prescriptions = Image("Prescriptions")
//    let reports = Image("Reports")
//    let tests = Image("Tests")
//    let instructions = Image("Instructions")
//    let medicines = Image("Medicines")
//    let checkupdetails = Image("CheckupDetails")
//    let checkup = Image("Checkups")
//    let addfood = Image("AddFood")
//let rectangle = Image("Rectangle")
//    let successpopup = Image("SuccessPopUp")
//    let unhatedheart = Image("UnhatedHeart")
//    let hatedheart = Image("HatedHeart")
//    let notfavoriteheart = Image("NotFavoriteHeart")
//    let notdislike = Image("NotDisLiked")
//    let selectedlike = Image("LikeSelected")
//    let thumbsup = Image("thumbsup")
//    let thumbsdown = Image("Thumbdown")
//    let linedHeart = Image("linedheart")
//    let badfood = Image("badFoods")
//    let fatdiary = Image("fullfatDiary")
//    let favoriteheart = Image("FavouriteHeart")
//    let shadedrectangle = Image("ShadedRectangle")
//    let whitevector = Image("WhiteVector")
//    let goodfood = Image("GoodFood")
//    let rightarrow = Image("RightArrow")
//    let ellipse1 = Image("Ellipse1")
//    let ellipse2 = Image("Ellipse2")
//    let filter = Image("Filter")
//    let diseasetick = Image("DiseaseTick")
//    let sophia = Image("Sophia")
//    let copyvector = Image("CopyVector")
//    let vector = Image("Vector")
//    let copy = Image("Copy")
//    let tickmark = Image("TickMark")
//    let groupimage = Image("groupPopup")
//    let calendar = Image("CalendarMonth")
//    let precaution = Image("Precaution")
//    let result = Image("Result")
//    let dislike = Image("Dislike")
//    let likes = Image ("Like")
//    let links = Image("Links")
//    let task = Image("Tasks")
//    let checkups = Image("Checkup")
//    let diseasedetails = Image("DiseaseDetails")
//    let guidevideo = Image("Guide")
//    let calendarmonth = Image("CalenderMonth")
//    let shedule = Image("Schedule")
//    let greenrectangle = Image("GreenRectangle")
//    let elipse1 = Image("Ellipse1")
//    let elipse2 = Image("Ellipse2")
//    let filterr = Image("Filter")
//    let calendarsidemenu = Image("CalendarSideMenu")
//    let food = Image("Food")
//    let linkcare = Image("LinkCare")
// //   let links = Image("Links")
//    let career = Image("Career")
//    let educare = Image("Educare")
//    let personality = Image("Personality")
//    let beauty = Image("Beauty")
//    let heart = Image("Heart")
//    let shopping = Image("Shopping")
//    let clockicon = Image("clockIcon")
//    let orderIcon = Image("Ordericon")
//    let QuestionCamera = Image("questioncamera")
//    let eyes = Image("Eye")
//    let daughter = Image("Daughter")
//    let mother = Image("mother")
//    let homelogo = Image("homelogo")
//    let dailytask = Image("dailytask")
//    let edwardpicture = Image("edwardpicture")
//    let homefilter = Image("Filter")
//    let homecamera = Image("camera?")
//    let HomescreenImage = Image("HomeScreenImage")
//    let sidemenu = Image("SideMenuBar")
//    let AvatarImage1 = Image("Avatar1")
//    let AvatarImage2 = Image("Avatar2")
//    let AvatarImage3 = Image("Avatar3")
//    let AvatarImage4 = Image("Avatar4")
//    let AvatarImage5 = Image("Avatar5") 
//    let SplashImage = Image("SplashImage")
//    let flag  = Image("Flag")
//    let ProfileCricle =  Image("ProfileCricle")
//    let Profile =  Image("ProfileImage")
//    let AddCricle =  Image("addcircle")
//    let ModeData =  Image("More")
//    let CropImage =  Image("Crop")
//    let CircleImage =  Image("CircleImage")
//    let Editprofile =  Image("Editprofile")
//    let Camrabackground =  Image("Camrabackground")
//    let Camra =  Image("Camra")
//    let menu =  Image("menu")
//    let Background =  Image("Background")
//    let map =  Image("map")
//    let Favorite =  Image("Favorite")
//    let Logout =  Image("Logout")
//    let Filter = Image("Filter")
//    let BlackMenu = Image("BlackMenu")
//    let homeTiktok = Image("homeTiktok")
//    let Will = Image("Will")
//    let spencer = Image("spencer")
//    let Starmap = Image("Starmap")
//    let favouriteicon = Image("favouriteicon")
//    let starYoutube = Image("StarYoutube")
//    let starTiktok = Image("StarTiktok")
//    let starinstagram = Image("Starinstagram")
//    let starSnack = Image("StarSnack")
//    let ALEX = Image("ALEX")
//    let deliveryTime = Image("deliveryTime")
//    let Subtract = Image("Subtract")
//    let Cliks = Image("Cliks")
//    let userImage = Image("userImage")
//    let Seen = Image("Seen")
//   // let filter = Image("filter")
//    let CategoriesImage = Image("CategoriesImage")
//    let FollowersImage = Image("FollowersImage")
//    let pricerange = Image("pricerange")
//    let plateforms = Image("plateforms")
//    let ConnectSport = Image("ConnectSport")
//    let Menu = Image("Menu")
//    let dost = Image("3 dost")
//    let Avatar = Image("Avatar")
//    let Mail = Image("Mail")
//    
//}
//
